#=============================================================================
# init.toml --- customize configuration example for SpaceVim
# Copyright (c) 2016-2020 
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "nil"
    buffer_index_type = 4
    windows_index_type = 3

    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # left sections of statusline
    statusline_left_sections = [
        'winnr',
#        'major mode',
#        'filename',
#        'fileformat'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'percentage'
    ]

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    default_indent = 4
    enable_cursorline = 0

    # customize option
    snippet_engine = "ultisnips"
    filemanager = "defx"
    # filemanager = "nerdtree"
    # autocomplete module
    autocomplete_method = "coc" # require enable lsp module
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    enable_neomake = false

    # disable built-in plugin
    # disabled_plugins = ["neomake.vim"]
    enable_vimfiler_welcome = false

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "cycle"
    auto_completion_enable_snippets_in_popup = true
    autocomplete_parens = true

[[layers]]
    name = "VersionControl"
    enable = false

[[layers]]
    name = "checkers"
    enable = false

[[layers]]
    name = "core#statusline"

[[layers]]
    name = "core#banner"
    enable = false

[[layers]]
    name = "core#tabline"

[[layers]]
    name = 'core'
    filetree_show_hidden = true

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "lang#c"
    clang_executable = "g++"
    clang_flag = ['-I/user/include']
    enable_clang_syntax_highlight = false

    [layer.clang_std]
        c = "c11"
        cpp = "c++1z"

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'cpp'
  ]
  [layers.override_cmd]
    c = ['ccls', '--log-file=/tmp/ccls.log']
    cpp = ['ccls', '--log-file=/tmp/ccls.log']

[[layers]]
    name = "format"

[[layers]]
    name = "edit"
    enable = false

# fuzzy search
[[layers]]
  name = "denite"
  enable = false

# fuzzy search
[[layers]]
  name = "fzf"
  enable = false

[[layers]]
    name = "cscope"
    enable = false

[[layers]]
    name = "gtags"
    gtagslabel = "pygments"
    enable = false

[[layers]]
    name = "ui"
    enable = false

# 基于lsp的高亮插件
#[[custom_plugins]]
#    name = 'jackguo380/vim-lsp-cxx-highlight'

# 主要用于快速搜索 文件, buffer 和 函数
[[custom_plugins]]
    name = "Yggdroot/LeaderF"
    build = "./install.sh"

# 参考https://vimjc.com/vim-indentLine-plugin.html
[[custom_plugins]]
    name = 'Yggdroot/indentLine'

# 从 http://cplusplus.com/ 和 http://cppreference.com/ 获取文档
[[custom_plugins]]
    name = 'skywind3000/vim-cppman'

[[custom_plugins]]
    repo = "dracula/vim"
    name = "dracula"
    merged = false

[[custom_plugins]]
    name = 'voldikss/vim-translator'

